# Generated by Django 4.1 on 2022-10-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0005_alter_team_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
    ]
